In [3]:
import selenium 
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

In [4]:
driver= webdriver.Chrome()
driver.get('https://www.google.com/')

In [5]:
url= 'https://www.naukri.com/'
driver.get(url)

In [6]:
designation= driver.find_element(By.CLASS_NAME,'suggestor-input')
designation.send_keys('Data Scientist')

In [7]:
location=driver.find_element(By.XPATH,'/html/body/div[1]/div[7]/div/div/div[5]/div/div/div/div[1]/div/input')
location.send_keys('Noida')

In [8]:
search=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search.click()

In [9]:
Designation = []
Company=[]
Skill=[]
Address=[]
Exeprience=[]
Qualification=[]

In [11]:
try:
    designtion=driver.find_elements(By.XPATH,'//a[@class="title "]')
    for i in designtion:
        Designation.append(i.text)
except NoSuchElementException:
    Designation.append('_')
except StaleElementReferenceException:
    Designation.append('_')
    
try:
    company=driver.find_elements(By.XPATH,'//a[@class=" comp-name mw-25"]')
    for i in company:
        Company.append(i.text)
except NoSuchElementException:
    Company.append('_')
except StaleElementReferenceException:
    Company.append('_')
try:
    skill=driver.find_elements(By.XPATH,'//div[@class=" row5"]')
    for i in skill:
        Skill.append(i.text)
except NoSuchElementException:
    Skill.append('_')
except StaleElementReferenceException:
    Skill.append('_')

try:
    address= driver.find_elements(By.XPATH,'//span[@class="loc-wrap ver-line"]')
    for i in address:
        Address.append(i.text)
except NoSuchElementException:
    Address.append('_')
except StaleElementReferenceException:
    Address.append('_')
try:
    exeprience=driver.find_elements(By.XPATH,'//span[@class="exp-wrap"]')
    for i in exeprience:
        Exeprience.append(i.text)
except NoSuchElementException:
    Exeprience.append('_')
except StaleElementReferenceException:
    Exeprience.append('_')
try:
    qulification=driver.find_elements(By.XPATH,'//div[@class=" row4"]')
    for i in qulification:
        Qualification.append(i.text)
except NoSuchElementException:
    Qualification.append('_')
except StaleElementReferenceException:
    Qualification.append('_')

In [14]:
a = {'Name_Des.': Designation,'COMPANY': Company,'SKILL_SET':Skill,'OFFICE_AD.': Address, 'EXEPRIENCE':Exeprience, 'DESCRIPTION':Qualification}
df = pd.DataFrame.from_dict(a, orient='index')
df = df.transpose()
print("JOB IN NOIDA SECTOR FOR DATA SCIENCE")
df

JOB IN NOIDA SECTOR FOR DATA SCIENCE

,Name_Des.,COMPANY,SKILL_SET,OFFICE_AD.,EXEPRIENCE,DESCRIPTION
0,Data Scientist II,Honeywell,Analytical skillsElectrical engineeringSystem ...,"Greater Noida, Bengaluru",4-6 Yrs,Qualifications: . Bachelors / Masters degree i...
1,Lead Data Scientist,Honeywell,Computer scienceData analysisStatistical model...,"Greater Noida, Bengaluru",6-9 Yrs,"In this role, you will impact the business by ..."
2,Sr . Data Scientist / Manager,Novitas Infotech,customer analyticsSocial mediaAgileCustomer se...,"Noida, Gurugram, Bengaluru",7-10 Yrs,. You should be comfortable managing work plan...
3,,Novitas Infotech,,,,
4,,R Systems International,,,,
5,,Dhurin,,,,
6,Data Scientist,Ericsson,Hiring for one of these companies,"Noida, New Delhi, Pune, Gurgaon/Gurugram, Bang...",,"Noida, New Delhi, Pune, Gurgaon/Gurugram, Bang..."
7,Sr. Data Scientist,R Systems International,Hiring for one of these companies,"Noida, Ghaziabad, New Delhi, Faridabad, Gurgao...",5-10 Yrs,"5-10 Yrs\nNoida, Ghaziabad, New Delhi, Faridab..."
8,Data Scientist,Ericsson,customer analyticsSocial mediaAgileCustomer se...,"Noida, Gurugram, Bengaluru",3-7 Yrs,. You should be comfortable managing work plan...
9,Lead MLOps Engineer,Nokia,pythonMLOpsAIMLdata scientistsRestful APIIT Ad...,"Noida, Pune",5-8 Yrs,Education / Certifications: . Bachelors degree...
10,Senior data scientist,Times Internet,Data analysisOperations researchVersion contro...,"Noida, Mumbai, Bengaluru",5-9 Yrs,Traits that will help you succeed: . You are f...
11,Data Scientist,Care Health Insurance (CHI),Text miningWeb analyticsArchitecturedata scien...,Noida,5-15 Yrs,"Familiarity with GCP, Real time data ingestion..."
12,Data Scientist - 4 Openings,PropTiger,Data ScienceData ScientistArtificial Intellige...,Hybrid - Noida,3-7 Yrs,Looking for experienced Data Scientist Candida...
13,Data Scientist,Honeywell,Text miningArchitectureWeb analyticsGCPNeural ...,Noida,5-7 Yrs,"Familiarity with GCP, Real time data ingestion..."
14,Data Scientist,Honeywell,TelecomData analysisAnalyticalMachine learning...,Noida,5-9 Yrs,Education: BE / B Tech in Computer Science / T...
15,Data Scientist,Novitas Infotech,Computer sciencedeep learningsparkMachine lear...,Noida,3-8 Yrs,. Bachelors or Masters degree in computer scie...
16,Principal Data Scientist / Sr. Data Scientist ...,Novitas Infotech,Machine LearningData ScienceTensorflowPredicti...,"Noida, Gurugram, Delhi / NCR",0-5 Yrs,Principal Data Scientist Sr Data Scientists Da...
17,Principal Data Scientist/Senior Data Scientist...,R Systems International,Data ScienceTensorflowNLPData ScientistArtific...,"Noida, Gurugram, Delhi / NCR",0-5 Yrs,Principal Data Scientist/Senior Data Scientist...
18,Hiring For DATA Scientist-Care Health Insurance,Dhurin,Data ScientistData EngineeringPower BiPython D...,"Noida, Gurugram, Delhi / NCR",2-5 Yrs,Qualification . Any graduate
19,Data Scientist,Ericsson,Critical ThinkingProblem SolvingMachine Learni...,"Hybrid - Noida, Gurugram, Delhi / NCR",1-4 Yrs,Who we are?REA India is a part of REA Group Lt...
20,Hiring | IT Services & Consulting | Data Scien...,R Systems International,Data ScienceData ScientistPysparkAzureHypothes...,"Noida, Kolkata, Hyderabad, Pune, Chennai, Mumb...",6-11 Yrs,"Data Analytics, Hypothesis testing, Machine le..."
21,Data Scientist -Image Analytics - (Multiple lo...,Ericsson,PythonOCRPytorchcomputer vision techniquesTens...,"Hybrid - Noida, Uttar Pradesh, Pune, Maharasht...",5-10 Yrs,Our esteemed client is seeking an exceptionall...
22,Hiring data scientist For leading MNC,Nokia,Data ScienceTensorflowAlgorithm DevelopmentCnn...,"Noida, Uttar Pradesh, Delhi / NCR, Mumbai (All...",0-5 Yrs,Data Collection: Gathering data from various s...
23,Data scientist / ML engineer -- US MNC (analyt...,Times Internet,PythonTensorflowPredictive ModelingMatplotlibP...,"Hybrid - Noida, Gurugram, Bengaluru",5-10 Yrs,Has experience working on unstructured data ( ...
24,Principal Data Scientist /Senior Data Scientis...,Care Health Insurance (CHI),Machine LearningData SciencePredictive Modelin...,"Noida, Gurugram, Delhi / NCR",0-5 Yrs,Principal Data Scientist / Senior Data Scienti...
25,Data Scientist II,PropTiger,Analytical skillsElectrical engineeringSystem ...,"Greater Noida, Bengaluru",None,None
26,Lead Data Scientist,None,Computer scienceData analysisStatistical model...,"Greater Noida, Bengaluru",None,None
27,Sr . Data Scientist / Manager,None,customer analyticsSocial mediaAgileCustomer se...,"Noida, Gurugram, Bengaluru",None,None
28,,None,,,None,None
29,,None,,,None,None
30,,None,,,None,None
31,Data Scientist,None,Hiring for one of these companies,"Noida, New Delhi, Pune, Gurgaon/Gurugram, Bang...",None,None
32,Sr. Data Scientist,None,Hiring for one of these companies,"Noida, Ghaziabad, New Delhi, Faridabad, Gurgao...",None,None
33,Data Scientist,None,customer analyticsSocial mediaAgileCustomer se...,"Noida, Gurugram, Bengaluru",None,None
34,Lead MLOps Engineer,None,pythonMLOpsAIMLdata scientistsRestful APIIT Ad...,"Noida, Pune",None,None
35,Senior data scientist,None,Data analysisOperations researchVersion contro...,"Noida, Mumbai, Bengaluru",None,None
36,Data Scientist,None,Text miningWeb analyticsArchitecturedata scien...,Noida,None,None
37,Data Scientist - 4 Openings,None,Data ScienceData ScientistArtificial Intellige...,Hybrid - Noida,None,None
38,Data Scientist,None,Text miningArchitectureWeb analyticsGCPNeural ...,Noida,None,None
39,Data Scientist,None,TelecomData analysisAnalyticalMachine learning...,Noida,None,None
40,Data Scientist,None,Computer sciencedeep learningsparkMachine lear...,Noida,None,None
41,Principal Data Scientist / Sr. Data Scientist ...,None,Machine LearningData ScienceTensorflowPredicti...,"Noida, Gurugram, Delhi / NCR",None,None
42,Principal Data Scientist/Senior Data Scientist...,None,Data ScienceTensorflowNLPData ScientistArtific...,"Noida, Gurugram, Delhi / NCR",None,None
43,Hiring For DATA Scientist-Care Health Insurance,None,Data ScientistData EngineeringPower BiPython D...,"Noida, Gurugram, Delhi / NCR",None,None
44,Data Scientist,None,Critical ThinkingProblem SolvingMachine Learni...,"Hybrid - Noida, Gurugram, Delhi / NCR",None,None
45,Hiring | IT Services & Consulting | Data Scien...,None,Data ScienceData ScientistPysparkAzureHypothes...,"Noida, Kolkata, Hyderabad, Pune, Chennai, Mumb...",None,None
46,Data Scientist -Image Analytics - (Multiple lo...,None,PythonOCRPytorchcomputer vision techniquesTens...,"Hybrid - Noida, Uttar Pradesh, Pune, Maharasht...",None,None
47,Hiring data scientist For leading MNC,None,Data ScienceTensorflowAlgorithm DevelopmentCnn...,"Noida, Uttar Pradesh, Delhi / NCR, Mumbai (All...",None,None
48,Data scientist / ML engineer -- US MNC (analyt...,None,PythonTensorflowPredictive ModelingMatplotlibP...,"Hybrid - Noida, Gurugram, Bengaluru",None,None
49,Principal Data Scientist /Senior Data Scientis...,None,Machine LearningData SciencePredictive Modelin...,"Noida, Gurugram, Delhi / NCR",None,None